fn_single_line = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true

# max_width = 75
chain_width = 30
struct_lit_width = 10
attr_fn_like_width = 25
fn_call_width = 40
struct_field_align_threshold = 20

control_brace_style = "ClosingNextLine"
fn_params_layout ="Tall"
imports_layout = "Vertical"
# indent_style = "Visual"
imports_granularity = "One"
group_imports = "StdExternalCrate"